version: "3.9"
services:
  dev:
    build: 
      context: ./dev
      args:
        GITCONFIG_EMAIL: ${GITCONFIG_EMAIL}
        GITCONFIG_NAME: ${GITCONFIG_NAME}
        REPO_URL: ${REPO_URL}
    ports:
      - ${LOCAL_PORT}:80
    tty: true
    restart: unless-stopped